/**
 * Permissions Configuration
 * Defines permissions for each module based on roles
 */

import { ROLES, Role } from "./roles.js";

/**
 * Permission actions
 */
export const ACTIONS = {
  CREATE: "create",
  READ: "read",
  UPDATE: "update",
  DELETE: "delete",
  APPROVE: "approve",
  EXPORT: "export",
  IMPORT: "import",
  PRINT: "print",
} as const;

export type Action = typeof ACTIONS[keyof typeof ACTIONS];

/**
 * Modules in the system
 */
export const MODULES = {
  SALES: "sales",
  PURCHASES: "purchases",
  INVENTORY: "inventory",
  BANKING: "banking",
  ACCOUNTANT: "accountant",
  PROJECTS: "projects",
  REPORTS: "reports",
  DOCUMENTS: "documents",
  SETTINGS: "settings",
  USERS: "users",
  ORGANIZATION: "organization",
} as const;

export type Module = typeof MODULES[keyof typeof MODULES];

/**
 * Permission matrix: role -> module -> actions
 */
const PERMISSIONS: Record<Role, Record<Module, Action[]>> = {
  [ROLES.OWNER]: {
    [MODULES.SALES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.IMPORT, ACTIONS.PRINT],
    [MODULES.PURCHASES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.IMPORT, ACTIONS.PRINT],
    [MODULES.INVENTORY]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.IMPORT, ACTIONS.PRINT],
    [MODULES.BANKING]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.IMPORT, ACTIONS.PRINT],
    [MODULES.ACCOUNTANT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.IMPORT, ACTIONS.PRINT],
    [MODULES.PROJECTS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.IMPORT, ACTIONS.PRINT],
    [MODULES.REPORTS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.DOCUMENTS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT, ACTIONS.IMPORT],
    [MODULES.SETTINGS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [MODULES.USERS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [MODULES.ORGANIZATION]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
  },
  [ROLES.ADMIN]: {
    [MODULES.SALES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.IMPORT, ACTIONS.PRINT],
    [MODULES.PURCHASES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.IMPORT, ACTIONS.PRINT],
    [MODULES.INVENTORY]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.IMPORT, ACTIONS.PRINT],
    [MODULES.BANKING]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.IMPORT, ACTIONS.PRINT],
    [MODULES.ACCOUNTANT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.IMPORT, ACTIONS.PRINT],
    [MODULES.PROJECTS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.IMPORT, ACTIONS.PRINT],
    [MODULES.REPORTS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.DOCUMENTS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.EXPORT, ACTIONS.IMPORT],
    [MODULES.SETTINGS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [MODULES.USERS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [MODULES.ORGANIZATION]: [ACTIONS.READ, ACTIONS.UPDATE], // Cannot delete organization
  },
  [ROLES.ACCOUNTANT]: {
    [MODULES.SALES]: [ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.PURCHASES]: [ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.INVENTORY]: [ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.BANKING]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.IMPORT, ACTIONS.PRINT],
    [MODULES.ACCOUNTANT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.IMPORT, ACTIONS.PRINT],
    [MODULES.PROJECTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.REPORTS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.DOCUMENTS]: [ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.SETTINGS]: [ACTIONS.READ],
    [MODULES.USERS]: [ACTIONS.READ],
    [MODULES.ORGANIZATION]: [ACTIONS.READ],
  },
  [ROLES.MANAGER]: {
    [MODULES.SALES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.PURCHASES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.APPROVE, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.INVENTORY]: [ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.BANKING]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.ACCOUNTANT]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.PROJECTS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.DOCUMENTS]: [ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.SETTINGS]: [ACTIONS.READ],
    [MODULES.USERS]: [ACTIONS.READ],
    [MODULES.ORGANIZATION]: [ACTIONS.READ],
  },
  [ROLES.STAFF]: {
    [MODULES.SALES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.PURCHASES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.INVENTORY]: [ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.BANKING]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.ACCOUNTANT]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.PROJECTS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.DOCUMENTS]: [ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.SETTINGS]: [],
    [MODULES.USERS]: [],
    [MODULES.ORGANIZATION]: [],
  },
  [ROLES.STAFF_ASSIGNED]: {
    [MODULES.SALES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.EXPORT, ACTIONS.PRINT], // Only assigned customers
    [MODULES.PURCHASES]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.INVENTORY]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.BANKING]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.ACCOUNTANT]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.PROJECTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.DOCUMENTS]: [ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.SETTINGS]: [],
    [MODULES.USERS]: [],
    [MODULES.ORGANIZATION]: [],
  },
  [ROLES.TIMESHEET_STAFF]: {
    [MODULES.SALES]: [],
    [MODULES.PURCHASES]: [],
    [MODULES.INVENTORY]: [],
    [MODULES.BANKING]: [],
    [MODULES.ACCOUNTANT]: [],
    [MODULES.PROJECTS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.EXPORT, ACTIONS.PRINT], // Only time tracking
    [MODULES.REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT], // Only time reports
    [MODULES.DOCUMENTS]: [],
    [MODULES.SETTINGS]: [],
    [MODULES.USERS]: [],
    [MODULES.ORGANIZATION]: [],
  },
  [ROLES.VIEWER]: {
    [MODULES.SALES]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.PURCHASES]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.INVENTORY]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.BANKING]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.ACCOUNTANT]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.PROJECTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.DOCUMENTS]: [ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.SETTINGS]: [ACTIONS.READ],
    [MODULES.USERS]: [ACTIONS.READ],
    [MODULES.ORGANIZATION]: [ACTIONS.READ],
  },
};

/**
 * Check if a role has permission for an action in a module
 * @param role - User role
 * @param module - Module name
 * @param action - Action to check
 * @returns True if permission exists
 */
export function hasPermission(role: string, module: string, action: string): boolean {
  const rolePermissions = PERMISSIONS[role as Role];
  if (!rolePermissions) return false;

  const modulePermissions = rolePermissions[module as Module];
  if (!modulePermissions) return false;

  return modulePermissions.includes(action as Action);
}

/**
 * Get all permissions for a role in a module
 * @param role - User role
 * @param module - Module name
 * @returns Array of allowed actions
 */
export function getModulePermissions(role: string, module: string): Action[] {
  const rolePermissions = PERMISSIONS[role as Role];
  if (!rolePermissions) return [];

  return rolePermissions[module as Module] || [];
}

export default {
  ACTIONS,
  MODULES,
  PERMISSIONS,
  hasPermission,
  getModulePermissions,
};

