export const TIMEZONES = [
    "(GMT -12:00) GMT-12:00 (Etc/GMT+12)",
    "(GMT -11:00) GMT-11:00 (Etc/GMT+11)",
    "(GMT -11:00) West Samoa Time (MIT)",
    "(GMT -11:00) West Samoa Time (Pacific/Apia)",
    "(GMT -11:00) Samoa Standard Time (Pacific/Midway)",
    "(GMT -11:00) Niue Time (Pacific/Niue)",
    "(GMT -11:00) Samoa Standard Time (Pacific/Pago_Pago)",
    "(GMT -11:00) Samoa Standard Time (Pacific/Samoa)",
    "(GMT -11:00) Samoa Standard Time (US/Samoa)",
    "(GMT -10:00) Hawaii-Aleutian Daylight Time (America/Adak)",
    "(GMT -10:00) Hawaii-Aleutian Daylight Time (America/Atka)",
    "(GMT -10:00) GMT-10:00 (Etc/GMT+10)",
    "(GMT -10:00) Hawaii Standard Time (HST)",
    "(GMT -10:00) Tokelau Time (Pacific/Fakaofo)",
    "(GMT -10:00) Hawaii Standard Time (Pacific/Honolulu)",
    "(GMT -10:00) Hawaii Standard Time (Pacific/Johnston)",
    "(GMT -10:00) Cook Is. Time (Pacific/Rarotonga)",
    "(GMT -10:00) Tahiti Time (Pacific/Tahiti)",
    "(GMT -10:00) Hawaii Standard Time (SystemV/HST10)",
    "(GMT -10:00) Hawaii-Aleutian Daylight Time (US/Aleutian)",
    "(GMT -10:00) Hawaii Standard Time (US/Hawaii)",
    "(GMT -9:30) Marquesas Time (Pacific/Marquesas)",
    "(GMT -9:00) Alaska Daylight Time (AST)",
    "(GMT -9:00) Alaska Daylight Time (America/Anchorage)",
    "(GMT -9:00) Alaska Daylight Time (America/Juneau)",
    "(GMT -9:00) Alaska Daylight Time (America/Nome)",
    "(GMT -9:00) Alaska Daylight Time (America/Yakutat)",
    "(GMT -9:00) GMT-09:00 (Etc/GMT+9)",
    "(GMT -9:00) Gambier Time (Pacific/Gambier)",
    "(GMT -9:00) Alaska Standard Time (SystemV/YST9)",
    "(GMT -9:00) Alaska Daylight Time (SystemV/YST9YDT)",
    "(GMT -9:00) Alaska Daylight Time (US/Alaska)",
    "(GMT -8:00) Pacific Daylight Time (America/Dawson)",
    "(GMT -8:00) Pacific Daylight Time (America/Ensenada)",
    "(GMT -8:00) Pacific Daylight Time (America/Los_Angeles)",
    "(GMT -8:00) Pacific Daylight Time (America/Tijuana)",
    "(GMT -8:00) Pacific Daylight Time (America/Vancouver)",
    "(GMT -8:00) Pacific Daylight Time (America/Whitehorse)",
    "(GMT -8:00) Pacific Daylight Time (Canada/Pacific)",
    "(GMT -8:00) Pacific Daylight Time (Canada/Yukon)",
    "(GMT -8:00) GMT-08:00 (Etc/GMT+8)",
    "(GMT -8:00) Pacific Daylight Time (Mexico/BajaNorte)",
    "(GMT -8:00) Pacific Daylight Time (PST)",
    "(GMT -8:00) Pacific Daylight Time (PST8PDT)",
    "(GMT -8:00) Pitcairn Standard Time (Pacific/Pitcairn)",
    "(GMT -8:00) Pacific Standard Time (SystemV/PST8)",
    "(GMT -8:00) Pacific Daylight Time (SystemV/PST8PDT)",
    "(GMT -8:00) Pacific Daylight Time (US/Pacific)",
    "(GMT -8:00) Pacific Daylight Time (US/Pacific-New)",
    "(GMT -7:00) Mountain Daylight Time (America/Boise)",
    "(GMT -7:00) Mountain Daylight Time (America/Cambridge_Bay)",
    "(GMT -7:00) Mountain Daylight Time (America/Chihuahua)",
    "(GMT -7:00) Mountain Standard Time (America/Dawson_Creek)",
    "(GMT -7:00) Mountain Daylight Time (America/Denver)",
    "(GMT -7:00) Mountain Daylight Time (America/Edmonton)",
    "(GMT -7:00) Mountain Standard Time (America/Hermosillo)",
    "(GMT -7:00) Mountain Daylight Time (America/Inuvik)",
    "(GMT -7:00) Mountain Daylight Time (America/Mazatlan)",
    "(GMT -7:00) Mountain Standard Time (America/Phoenix)",
    "(GMT -7:00) Mountain Daylight Time (America/Shiprock)",
    "(GMT -7:00) Mountain Daylight Time (America/Yellowknife)",
    "(GMT -7:00) Mountain Daylight Time (Canada/Mountain)",
    "(GMT -7:00) GMT-07:00 (Etc/GMT+7)",
    "(GMT -7:00) Mountain Standard Time (MST)",
    "(GMT -7:00) Mountain Daylight Time (MST7MDT)",
    "(GMT -7:00) Mountain Daylight Time (Mexico/BajaSur)",
    "(GMT -7:00) Mountain Daylight Time (Navajo)",
    "(GMT -7:00) Mountain Standard Time (PNT)",
    "(GMT -7:00) Mountain Standard Time (SystemV/MST7)",
    "(GMT -7:00) Mountain Daylight Time (SystemV/MST7MDT)",
    "(GMT -7:00) Mountain Standard Time (US/Arizona)",
    "(GMT -7:00) Mountain Daylight Time (US/Mountain)",
    "(GMT -6:00) Central Standard Time (America/Belize)",
    "(GMT -6:00) Central Daylight Time (America/Cancun)",
    "(GMT -6:00) Central Daylight Time (America/Chicago)",
    "(GMT -6:00) Central Standard Time (America/Costa_Rica)",
    "(GMT -6:00) Central Standard Time (America/El_Salvador)",
    "(GMT -6:00) Central Standard Time (America/Guatemala)",
    "(GMT -6:00) Central Daylight Time (America/Indiana/Knox)",
    "(GMT -6:00) Central Daylight Time (America/Indiana/Petersburg)",
    "(GMT -6:00) Central Daylight Time (America/Indiana/Vincennes)",
    "(GMT -6:00) Eastern Daylight Time (America/Knox_IN)",
    "(GMT -6:00) Central Standard Time (America/Managua)",
    "(GMT -6:00) Central Daylight Time (America/Menominee)",
    "(GMT -6:00) Central Daylight Time (America/Merida)",
    "(GMT -6:00) Central Daylight Time (America/Mexico_City)",
    "(GMT -6:00) Central Daylight Time (America/Monterrey)",
    "(GMT -6:00) Central Daylight Time (America/North_Dakota/Center)",
    "(GMT -6:00) Central Daylight Time (America/North_Dakota/New_Salem)",
    "(GMT -6:00) Central Daylight Time (America/Rainy_River)",
    "(GMT -6:00) Central Daylight Time (America/Rankin_Inlet)",
    "(GMT -6:00) Central Standard Time (America/Regina)",
    "(GMT -6:00) Central Standard Time (America/Swift_Current)",
    "(GMT -6:00) Central Standard Time (America/Tegucigalpa)",
    "(GMT -6:00) Central Daylight Time (America/Winnipeg)",
    "(GMT -6:00) Central Daylight Time (CST)",
    "(GMT -6:00) Central Daylight Time (CST6CDT)",
    "(GMT -6:00) Central Daylight Time (Canada/Central)",
    "(GMT -6:00) Central Standard Time (Canada/East-Saskatchewan)",
    "(GMT -6:00) Central Standard Time (Canada/Saskatchewan)",
    "(GMT -6:00) Easter Is. Time (Chile/EasterIsland)",
    "(GMT -6:00) GMT-06:00 (Etc/GMT+6)",
    "(GMT -6:00) Central Daylight Time (Mexico/General)",
    "(GMT -6:00) Easter Is. Time (Pacific/Easter)",
    "(GMT -6:00) Galapagos Time (Pacific/Galapagos)",
    "(GMT -6:00) Central Standard Time (SystemV/CST6)",
    "(GMT -6:00) Central Daylight Time (SystemV/CST6CDT)",
    "(GMT -6:00) Central Daylight Time (US/Central)",
    "(GMT -6:00) Eastern Daylight Time (US/Indiana-Starke)",
    "(GMT -5:00) Eastern Standard Time (America/Atikokan)",
    "(GMT -5:00) Colombia Time (America/Bogota)",
    "(GMT -5:00) Eastern Standard Time (America/Cayman)",
    "(GMT -5:00) Eastern Standard Time (America/Coral_Harbour)",
    "(GMT -5:00) Eastern Daylight Time (America/Detroit)",
    "(GMT -5:00) Acre Time (America/Eirunepe)",
    "(GMT -5:00) Eastern Daylight Time (America/Fort_Wayne)",
    "(GMT -5:00) Eastern Daylight Time (America/Grand_Turk)",
    "(GMT -5:00) Ecuador Time (America/Guayaquil)",
    "(GMT -5:00) Central Daylight Time (America/Havana)",
    "(GMT -5:00) Eastern Daylight Time (America/Indiana/Indianapolis)",
    "(GMT -5:00) Eastern Daylight Time (America/Indiana/Marengo)",
    "(GMT -5:00) Eastern Daylight Time (America/Indiana/Vevay)",
    "(GMT -5:00) Eastern Daylight Time (America/Indianapolis)",
    "(GMT -5:00) Eastern Daylight Time (America/Iqaluit)",
    "(GMT -5:00) Eastern Standard Time (America/Jamaica)",
    "(GMT -5:00) Eastern Daylight Time (America/Kentucky/Louisville)",
    "(GMT -5:00) Eastern Daylight Time (America/Kentucky/Monticello)",
    "(GMT -5:00) Peru Time (America/Lima)",
    "(GMT -5:00) Eastern Daylight Time (America/Louisville)",
    "(GMT -5:00) Central Daylight Time (America/Matamoros)",
    "(GMT -5:00) Eastern Daylight Time (America/Montreal)",
    "(GMT -5:00) Eastern Daylight Time (America/Nassau)",
    "(GMT -5:00) Eastern Daylight Time (America/New_York)",
    "(GMT -5:00) Eastern Daylight Time (America/Nipigon)",
    "(GMT -5:00) Eastern Standard Time (America/Panama)",
    "(GMT -5:00) Eastern Daylight Time (America/Pangnirtung)",
    "(GMT -5:00) Eastern Daylight Time (America/Port-au-Prince)",
    "(GMT -5:00) Acre Time (America/Porto_Acre)",
    "(GMT -5:00) Acre Time (America/Rio_Branco)",
    "(GMT -5:00) Eastern Daylight Time (America/Thunder_Bay)",
    "(GMT -5:00) Eastern Daylight Time (America/Toronto)",
    "(GMT -5:00) Acre Time (Brazil/Acre)",
    "(GMT -5:00) Eastern Daylight Time (Canada/Eastern)",
    "(GMT -5:00) Central Daylight Time (Cuba)",
    "(GMT -5:00) Eastern Standard Time (EST)",
    "(GMT -5:00) Eastern Daylight Time (EST5EDT)",
    "(GMT -5:00) GMT-05:00 (Etc/GMT+5)",
    "(GMT -5:00) Eastern Daylight Time (IET)",
    "(GMT -5:00) Eastern Standard Time (Jamaica)",
    "(GMT -5:00) Eastern Standard Time (SystemV/EST5)",
    "(GMT -5:00) Eastern Daylight Time (SystemV/EST5EDT)",
    "(GMT -5:00) Eastern Daylight Time (US/East-Indiana)",
    "(GMT -5:00) Eastern Daylight Time (US/Eastern)",
    "(GMT -5:00) Eastern Daylight Time (US/Michigan)",
    "(GMT -4:00) Atlantic Standard Time (America/Anguilla)",
    "(GMT -4:00) Atlantic Standard Time (America/Antigua)",
    "(GMT -4:00) Atlantic Standard Time (America/Aruba)",
    "(GMT -4:00) Paraguay Time (America/Asuncion)",
    "(GMT -4:00) Atlantic Standard Time (America/Barbados)",
    "(GMT -4:00) Atlantic Standard Time (America/Blanc-Sablon)",
    "(GMT -4:00) Amazon Time (America/Boa_Vista)",
    "(GMT -4:00) Amazon Time (America/Campo_Grande)",
    "(GMT -4:00) Venezuela Time (America/Caracas)",
    "(GMT -4:00) Amazon Time (America/Cuiaba)",
    "(GMT -4:00) Atlantic Standard Time (America/Curacao)",
    "(GMT -4:00) Atlantic Standard Time (America/Dominica)",
    "(GMT -4:00) Atlantic Daylight Time (America/Glace_Bay)",
    "(GMT -4:00) Atlantic Daylight Time (America/Goose_Bay)",
    "(GMT -4:00) Atlantic Standard Time (America/Grenada)",
    "(GMT -4:00) Atlantic Standard Time (America/Guadeloupe)",
    "(GMT -4:00) Guyana Time (America/Guyana)",
    "(GMT -4:00) Atlantic Daylight Time (America/Halifax)",
    "(GMT -4:00) Bolivia Time (America/La_Paz)",
    "(GMT -4:00) Amazon Time (America/Manaus)",
    "(GMT -4:00) Atlantic Standard Time (America/Martinique)",
    "(GMT -4:00) Atlantic Daylight Time (America/Moncton)",
    "(GMT -4:00) Atlantic Standard Time (America/Montserrat)",
    "(GMT -4:00) Atlantic Standard Time (America/Port_of_Spain)",
    "(GMT -4:00) Amazon Time (America/Porto_Velho)",
    "(GMT -4:00) Atlantic Standard Time (America/Puerto_Rico)",
    "(GMT -4:00) Chile Time (America/Santiago)",
    "(GMT -4:00) Atlantic Standard Time (America/Santo_Domingo)",
    "(GMT -4:00) Atlantic Standard Time (America/St_Kitts)",
    "(GMT -4:00) Atlantic Standard Time (America/St_Lucia)",
    "(GMT -4:00) Atlantic Standard Time (America/St_Thomas)",
    "(GMT -4:00) Atlantic Standard Time (America/St_Vincent)",
    "(GMT -4:00) Atlantic Daylight Time (America/Thule)",
    "(GMT -4:00) Atlantic Standard Time (America/Tortola)",
    "(GMT -4:00) Atlantic Standard Time (America/Virgin)",
    "(GMT -4:00) Chile Time (Antarctica/Palmer)",
    "(GMT -4:00) Atlantic Daylight Time (Atlantic/Bermuda)",
    "(GMT -4:00) Falkland Is. Summer Time (Atlantic/Stanley)",
    "(GMT -4:00) Amazon Time (Brazil/West)",
    "(GMT -4:00) Atlantic Daylight Time (Canada/Atlantic)",
    "(GMT -4:00) Chile Time (Chile/Continental)",
    "(GMT -4:00) GMT-04:00 (Etc/GMT+4)",
    "(GMT -4:00) Atlantic Standard Time (PRT)",
    "(GMT -4:00) Atlantic Standard Time (SystemV/AST4)",
    "(GMT -4:00) Atlantic Daylight Time (SystemV/AST4ADT)",
    "(GMT -3:30) Newfoundland Daylight Time (America/St_Johns)",
    "(GMT -3:30) Newfoundland Daylight Time (CNT)",
    "(GMT -3:30) Newfoundland Daylight Time (Canada/Newfoundland)",
    "(GMT -3:00) Argentine Time (AGT)",
    "(GMT -3:00) Brasilia Time (America/Araguaina)",
    "(GMT -3:00) Argentine Time (America/Argentina/Buenos_Aires)",
    "(GMT -3:00) Argentine Time (America/Argentina/Catamarca)",
    "(GMT -3:00) Argentine Time (America/Argentina/ComodRivadavia)",
    "(GMT -3:00) Argentine Time (America/Argentina/Cordoba)",
    "(GMT -3:00) Argentine Time (America/Argentina/Jujuy)",
    "(GMT -3:00) Argentine Time (America/Argentina/La_Rioja)",
    "(GMT -3:00) Argentine Time (America/Argentina/Mendoza)",
    "(GMT -3:00) Argentine Time (America/Argentina/Rio_Gallegos)",
    "(GMT -3:00) Argentine Time (America/Argentina/San_Juan)",
    "(GMT -3:00) Argentine Time (America/Argentina/Tucuman)",
    "(GMT -3:00) Argentine Time (America/Argentina/Ushuaia)",
    "(GMT -3:00) Brasilia Time (America/Bahia)",
    "(GMT -3:00) Brasilia Time (America/Belem)",
    "(GMT -3:00) Argentine Time (America/Buenos_Aires)",
    "(GMT -3:00) Argentine Time (America/Catamarca)",
    "(GMT -3:00) French Guiana Time (America/Cayenne)",
    "(GMT -3:00) Argentine Time (America/Cordoba)",
    "(GMT -3:00) Brasilia Time (America/Fortaleza)",
    "(GMT -3:00) Western Greenland Summer Time (America/Godthab)",
    "(GMT -3:00) Argentine Time (America/Jujuy)",
    "(GMT -3:00) Brasilia Time (America/Maceio)",
    "(GMT -3:00) Argentine Time (America/Mendoza)",
    "(GMT -3:00) Pierre & Miquelon Daylight Time (America/Miquelon)",
    "(GMT -3:00) Uruguay Time (America/Montevideo)",
    "(GMT -3:00) Suriname Time (America/Paramaribo)",
    "(GMT -3:00) Brasilia Time (America/Recife)",
    "(GMT -3:00) Argentine Time (America/Rosario)",
    "(GMT -3:00) Brasilia Time (America/Sao_Paulo)",
    "(GMT -3:00) Rothera Time (Antarctica/Rothera)",
    "(GMT -3:00) Brasilia Time (BET)",
    "(GMT -3:00) Brasilia Time (Brazil/East)",
    "(GMT -3:00) GMT-03:00 (Etc/GMT+3)",
    "(GMT -2:00) Fernando de Noronha Time (America/Noronha)",
    "(GMT -2:00) South Georgia Standard Time (Atlantic/South_Georgia)",
    "(GMT -2:00) Fernando de Noronha Time (Brazil/DeNoronha)",
    "(GMT -2:00) GMT-02:00 (Etc/GMT+2)",
    "(GMT -1:00) Eastern Greenland Summer Time (America/Scoresbysund)",
    "(GMT -1:00) Azores Summer Time (Atlantic/Azores)",
    "(GMT -1:00) Cape Verde Time (Atlantic/Cape_Verde)",
    "(GMT -1:00) GMT-01:00 (Etc/GMT+1)",
    "(GMT 0:00) Greenwich Mean Time (Africa/Abidjan)",
    "(GMT 0:00) Greenwich Mean Time (Africa/Accra)",
    "(GMT 0:00) Greenwich Mean Time (Africa/Bamako)",
    "(GMT 0:00) Greenwich Mean Time (Africa/Banjul)",
    "(GMT 0:00) Greenwich Mean Time (Africa/Bissau)",
    "(GMT 0:00) Western European Time (Africa/Casablanca)",
    "(GMT 0:00) Greenwich Mean Time (Africa/Conakry)",
    "(GMT 0:00) Greenwich Mean Time (Africa/Dakar)",
    "(GMT 0:00) Western European Time (Africa/El_Aaiun)",
    "(GMT 0:00) Greenwich Mean Time (Africa/Freetown)",
    "(GMT 0:00) Greenwich Mean Time (Africa/Lome)",
    "(GMT 0:00) Greenwich Mean Time (Africa/Monrovia)",
    "(GMT 0:00) Greenwich Mean Time (Africa/Nouakchott)",
    "(GMT 0:00) Greenwich Mean Time (Africa/Ouagadougou)",
    "(GMT 0:00) Greenwich Mean Time (Africa/Sao_Tome)",
    "(GMT 0:00) Greenwich Mean Time (Africa/Timbuktu)",
    "(GMT 0:00) Greenwich Mean Time (America/Danmarkshavn)",
    "(GMT 0:00) Western European Summer Time (Atlantic/Canary)",
    "(GMT 0:00) Western European Summer Time (Atlantic/Faeroe)",
    "(GMT 0:00) Western European Summer Time (Atlantic/Madeira)",
    "(GMT 0:00) Greenwich Mean Time (Atlantic/Reykjavik)",
    "(GMT 0:00) Greenwich Mean Time (Atlantic/St_Helena)",
    "(GMT 0:00) Irish Summer Time (Eire)",
    "(GMT 0:00) GMT+00:00 (Etc/GMT)",
    "(GMT 0:00) GMT+00:00 (Etc/GMT+0)",
    "(GMT 0:00) GMT+00:00 (Etc/GMT-0)",
    "(GMT 0:00) GMT+00:00 (Etc/GMT0)",
    "(GMT 0:00) Greenwich Mean Time (Etc/Greenwich)",
    "(GMT 0:00) Coordinated Universal Time (Etc/UCT)",
    "(GMT 0:00) Coordinated Universal Time (Etc/UTC)",
    "(GMT 0:00) Coordinated Universal Time (Etc/Universal)",
    "(GMT 0:00) Coordinated Universal Time (Etc/Zulu)",
    "(GMT 0:00) British Summer Time (Europe/Belfast)",
    "(GMT 0:00) Irish Summer Time (Europe/Dublin)",
    "(GMT 0:00) British Summer Time (Europe/Guernsey)",
    "(GMT 0:00) British Summer Time (Europe/Isle_of_Man)",
    "(GMT 0:00) British Summer Time (Europe/Jersey)",
    "(GMT 0:00) Western European Summer Time (Europe/Lisbon)",
    "(GMT 0:00) British Summer Time (Europe/London)",
    "(GMT 0:00) British Summer Time (GB)",
    "(GMT 0:00) British Summer Time (GB-Eire)",
    "(GMT 0:00) Greenwich Mean Time (GMT)",
    "(GMT 0:00) GMT+00:00 (GMT0)",
    "(GMT 0:00) Greenwich Mean Time (Greenwich)",
    "(GMT 0:00) Greenwich Mean Time (Iceland)",
    "(GMT 0:00) Western European Summer Time (Portugal)",
    "(GMT 0:00) Coordinated Universal Time (UCT)",
    "(GMT 0:00) Coordinated Universal Time (UTC)",
    "(GMT 0:00) Coordinated Universal Time (Universal)",
    "(GMT 0:00) Western European Summer Time (WET)",
    "(GMT 0:00) Coordinated Universal Time (Zulu)",
    "(GMT 1:00) Central European Time (Africa/Algiers)",
    "(GMT 1:00) Western African Time (Africa/Bangui)",
    "(GMT 1:00) Western African Time (Africa/Brazzaville)",
    "(GMT 1:00) Central European Summer Time (Africa/Ceuta)",
    "(GMT 1:00) Western African Time (Africa/Douala)",
    "(GMT 1:00) Western African Time (Africa/Kinshasa)",
    "(GMT 1:00) Western African Time (Africa/Lagos)",
    "(GMT 1:00) Western African Time (Africa/Libreville)",
    "(GMT 1:00) Western African Time (Africa/Luanda)",
    "(GMT 1:00) Western African Time (Africa/Malabo)",
    "(GMT 1:00) Western African Time (Africa/Ndjamena)",
    "(GMT 1:00) Western African Time (Africa/Niamey)",
    "(GMT 1:00) Western African Time (Africa/Porto-Novo)",
    "(GMT 1:00) Central European Summer Time (Africa/Tunis)",
    "(GMT 1:00) Western African Summer Time (Africa/Windhoek)",
    "(GMT 1:00) Central European Summer Time (Arctic/Longyearbyen)",
    "(GMT 1:00) Central European Summer Time (Atlantic/Jan_Mayen)",
    "(GMT 1:00) Central European Summer Time (CET)",
    "(GMT 1:00) Central European Summer Time (ECT)",
    "(GMT 1:00) GMT+01:00 (Etc/GMT-1)",
    "(GMT 1:00) Central European Summer Time (Europe/Amsterdam)",
    "(GMT 1:00) Central European Summer Time (Europe/Andorra)",
    "(GMT 1:00) Central European Summer Time (Europe/Belgrade)",
    "(GMT 1:00) Central European Summer Time (Europe/Berlin)",
    "(GMT 1:00) Central European Summer Time (Europe/Bratislava)",
    "(GMT 1:00) Central European Summer Time (Europe/Brussels)",
    "(GMT 1:00) Central European Summer Time (Europe/Budapest)",
    "(GMT 1:00) Central European Summer Time (Europe/Copenhagen)",
    "(GMT 1:00) Central European Summer Time (Europe/Gibraltar)",
    "(GMT 1:00) Central European Summer Time (Europe/Ljubljana)",
    "(GMT 1:00) Central European Summer Time (Europe/Luxembourg)",
    "(GMT 1:00) Central European Summer Time (Europe/Madrid)",
    "(GMT 1:00) Central European Summer Time (Europe/Malta)",
    "(GMT 1:00) Central European Summer Time (Europe/Monaco)",
    "(GMT 1:00) Central European Summer Time (Europe/Oslo)",
    "(GMT 1:00) Central European Summer Time (Europe/Paris)",
    "(GMT 1:00) Central European Summer Time (Europe/Podgorica)",
    "(GMT 1:00) Central European Summer Time (Europe/Prague)",
    "(GMT 1:00) Central European Summer Time (Europe/Rome)",
    "(GMT 1:00) Central European Summer Time (Europe/San_Marino)",
    "(GMT 1:00) Central European Summer Time (Europe/Sarajevo)",
    "(GMT 1:00) Central European Summer Time (Europe/Skopje)",
    "(GMT 1:00) Central European Summer Time (Europe/Stockholm)",
    "(GMT 1:00) Central European Summer Time (Europe/Tirane)",
    "(GMT 1:00) Central European Summer Time (Europe/Vaduz)",
    "(GMT 1:00) Central European Summer Time (Europe/Vatican)",
    "(GMT 1:00) Central European Summer Time (Europe/Vienna)",
    "(GMT 1:00) Central European Summer Time (Europe/Warsaw)",
    "(GMT 1:00) Central European Summer Time (Europe/Zagreb)",
    "(GMT 1:00) Central European Summer Time (Europe/Zurich)",
    "(GMT 1:00) Middle Europe Summer Time (MET)",
    "(GMT 1:00) Central European Summer Time (Poland)",
    "(GMT 2:00) Eastern European Summer Time (ART)",
    "(GMT 2:00) Central African Time (Africa/Blantyre)",
    "(GMT 2:00) Central African Time (Africa/Bujumbura)",
    "(GMT 2:00) Eastern European Summer Time (Africa/Cairo)",
    "(GMT 2:00) Central African Time (Africa/Gaborone)",
    "(GMT 2:00) Central African Time (Africa/Harare)",
    "(GMT 2:00) South Africa Standard Time (Africa/Johannesburg)",
    "(GMT 2:00) Central African Time (Africa/Kigali)",
    "(GMT 2:00) Central African Time (Africa/Lubumbashi)",
    "(GMT 2:00) Central African Time (Africa/Lusaka)",
    "(GMT 2:00) Central African Time (Africa/Maputo)",
    "(GMT 2:00) South Africa Standard Time (Africa/Maseru)",
    "(GMT 2:00) South Africa Standard Time (Africa/Mbabane)",
    "(GMT 2:00) Eastern European Time (Africa/Tripoli)",
    "(GMT 2:00) Eastern European Summer Time (Asia/Amman)",
    "(GMT 2:00) Eastern European Summer Time (Asia/Beirut)",
    "(GMT 2:00) Eastern European Summer Time (Asia/Damascus)",
    "(GMT 2:00) Eastern European Summer Time (Asia/Gaza)",
    "(GMT 2:00) Eastern European Summer Time (Asia/Istanbul)",
    "(GMT 2:00) Israel Standard Time (Asia/Jerusalem)",
    "(GMT 2:00) Eastern European Summer Time (Asia/Nicosia)",
    "(GMT 2:00) Israel Standard Time (Asia/Tel_Aviv)",
    "(GMT 2:00) Central African Time (CAT)",
    "(GMT 2:00) Eastern European Summer Time (EET)",
    "(GMT 2:00) Eastern European Summer Time (Egypt)",
    "(GMT+02:00) GMT+02:00 (Etc/GMT-2)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Athens)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Bucharest)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Chisinau)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Helsinki)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Istanbul)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Kaliningrad)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Kiev)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Mariehamn)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Minsk)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Nicosia)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Riga)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Simferopol)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Sofia)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Tallinn)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Tiraspol)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Uzhgorod)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Vilnius)",
    "(GMT 2:00) Eastern European Summer Time (Europe/Zaporozhye)",
    "(GMT 2:00) Israel Standard Time (Israel)",
    "(GMT 2:00) Eastern European Time (Libya)",
    "(GMT 2:00) Eastern European Summer Time (Türkiye)",
    "(GMT 3:00) Eastern African Time (Africa/Addis_Ababa)",
    "(GMT 3:00) Eastern African Time (Africa/Asmera)",
    "(GMT 3:00) Eastern African Time (Africa/Dar_es_Salaam)",
    "(GMT 3:00) Eastern African Time (Africa/Djibouti)",
    "(GMT 3:00) Eastern African Time (Africa/Kampala)",
    "(GMT 2:00) Central African Time (Africa/Khartoum)",
    "(GMT 3:00) Eastern African Time (Africa/Mogadishu)",
    "(GMT 3:00) Eastern African Time (Africa/Nairobi)",
    "(GMT 3:00) Syowa Time (Antarctica/Syowa)",
    "(GMT 3:00) Arabia Standard Time (Asia/Aden)",
    "(GMT 3:00) Arabia Daylight Time (Asia/Baghdad)",
    "(GMT 3:00) Arabia Standard Time (Asia/Bahrain)",
    "(GMT 3:00) Arabia Standard Time (Asia/Kuwait)",
    "(GMT 3:00) Arabia Standard Time (Asia/Qatar)",
    "(GMT 3:00) Arabia Standard Time (Asia/Riyadh)",
    "(GMT 3:00) Eastern African Time (EAT)",
    "(GMT+03:00) GMT+03:00 (Etc/GMT-3)",
    "(GMT 3:00) Moscow Daylight Time (Europe/Moscow)",
    "(GMT 3:00) Volgograd Summer Time (Europe/Volgograd)",
    "(GMT 3:00) Eastern African Time (Indian/Antananarivo)",
    "(GMT 3:00) Eastern African Time (Indian/Comoro)",
    "(GMT 3:00) Eastern African Time (Indian/Mayotte)",
    "(GMT 3:00) Moscow Daylight Time (W-SU)",
    "(GMT 3:07) GMT+03:07 (Asia/Riyadh87)",
    "(GMT 3:07) GMT+03:07 (Asia/Riyadh88)",
    "(GMT 3:07) GMT+03:07 (Asia/Riyadh89)",
    "(GMT 3:07) GMT+03:07 (Mideast/Riyadh87)",
    "(GMT 3:07) GMT+03:07 (Mideast/Riyadh88)",
    "(GMT 3:07) GMT+03:07 (Mideast/Riyadh89)",
    "(GMT 3:30) Iran Standard Time (Asia/Tehran)",
    "(GMT 3:30) Iran Standard Time (Iran)",
    "(GMT 4:00) Azerbaijan Summer Time (Asia/Baku)",
    "(GMT 4:00) Gulf Standard Time (Asia/Dubai)",
    "(GMT 4:00) Gulf Standard Time (Asia/Muscat)",
    "(GMT 4:00) Georgia Time (Asia/Tbilisi)",
    "(GMT 4:00) Armenia Summer Time (Asia/Yerevan)",
    "(GMT+04:00) GMT+04:00 (Etc/GMT-4)",
    "(GMT 4:00) Samara Summer Time (Europe/Samara)",
    "(GMT 4:00) Seychelles Time (Indian/Mahe)",
    "(GMT 4:00) Mauritius Time (Indian/Mauritius)",
    "(GMT 4:00) Reunion Time (Indian/Reunion)",
    "(GMT 4:00) Armenia Summer Time (NET)",
    "(GMT 4:30) Afghanistan Time (Asia/Kabul)",
    "(GMT 5:00) Aqtau Time (Asia/Aqtau)",
    "(GMT 5:00) Aqtobe Time (Asia/Aqtobe)",
    "(GMT 5:00) Turkmenistan Time (Asia/Ashgabat)",
    "(GMT 5:00) Turkmenistan Time (Asia/Ashkhabad)",
    "(GMT 5:00) Tajikistan Time (Asia/Dushanbe)",
    "(GMT 5:00) Pakistan Time (Asia/Karachi)",
    "(GMT 5:00) Oral Time (Asia/Oral)",
    "(GMT 5:00) Uzbekistan Time (Asia/Samarkand)",
    "(GMT 5:00) Uzbekistan Time (Asia/Tashkent)",
    "(GMT 5:00) Yekaterinburg Summer Time (Asia/Yekaterinburg)",
    "(GMT+05:00) GMT+05:00 (Etc/GMT-5)",
    "(GMT 5:00) French Southern & Antarctic Lands Time (Indian/Kerguelen)",
    "(GMT 5:00) Maldives Time (Indian/Maldives)",
    "(GMT 5:00) Pakistan Time (PLT)",
    "(GMT 5:30) India Standard Time (Asia/Calcutta)",
    "(GMT 5:30) Sri Lanka Time (Asia/Colombo)",
    "(GMT 5:30) India Standard Time (Asia/Kolkata)",
    "(GMT 5:30) India Standard Time (IST)",
    "(GMT 5:45) Nepal Time (Asia/Katmandu)",
    "(GMT 6:00) Mawson Time (Antarctica/Mawson)",
    "(GMT 6:00) Vostok Time (Antarctica/Vostok)",
    "(GMT 6:00) Alma-Ata Time (Asia/Almaty)",
    "(GMT 6:00) Kirgizstan Time (Asia/Bishkek)",
    "(GMT 6:00) Bangladesh Time (Asia/Dacca)",
    "(GMT 6:00) Bangladesh Time (Asia/Dhaka)",
    "(GMT 6:00) Novosibirsk Summer Time (Asia/Novosibirsk)",
    "(GMT 6:00) Omsk Summer Time (Asia/Omsk)",
    "(GMT 6:00) Qyzylorda Time (Asia/Qyzylorda)",
    "(GMT 6:00) Bhutan Time (Asia/Thimbu)",
    "(GMT 6:00) Bhutan Time (Asia/Thimphu)",
    "(GMT 6:00) Bangladesh Time (BST)",
    "(GMT+06:00) GMT+06:00 (Etc/GMT-6)",
    "(GMT 6:00) Indian Ocean Territory Time (Indian/Chagos)",
    "(GMT 6:30) Myanmar Time (Asia/Rangoon)",
    "(GMT 6:30) Cocos Islands Time (Indian/Cocos)",
    "(GMT 7:00) Davis Time (Antarctica/Davis)",
    "(GMT 7:00) Indochina Time (Asia/Bangkok)",
    "(GMT 7:00) Indochina Time (Asia/Ho_Chi_Minh)",
    "(GMT 7:00) Hovd Summer Time (Asia/Hovd)",
    "(GMT 7:00) West Indonesia Time (Asia/Jakarta)",
    "(GMT 7:00) Krasnoyarsk Summer Time (Asia/Krasnoyarsk)",
    "(GMT 7:00) Indochina Time (Asia/Phnom_Penh)",
    "(GMT 7:00) West Indonesia Time (Asia/Pontianak)",
    "(GMT 7:00) Indochina Time (Asia/Saigon)",
    "(GMT 7:00) Indochina Time (Asia/Vientiane)",
    "(GMT+07:00) GMT+07:00 (Etc/GMT-7)",
    "(GMT 7:00) Christmas Island Time (Indian/Christmas)",
    "(GMT 7:00) Indochina Time (VST)",
    "(GMT 8:00) Western Standard Time (Australia)(Antarctica/Casey)",
    "(GMT 8:00) Brunei Time (Asia/Brunei)",
    "(GMT 8:00) China Standard Time (Asia/Chongqing)",
    "(GMT 8:00) China Standard Time (Asia/Harbin)",
    "(GMT 8:00) Hong Kong Time (Asia/Hong_Kong)",
    "(GMT 8:00) Irkutsk Summer Time (Asia/Irkutsk)",
    "(GMT 8:00) China Standard Time (Asia/Kashgar)",
    "(GMT 8:00) Malaysia Time (Asia/Kuala_Lumpur)",
    "(GMT 8:00) Malaysia Time (Asia/Kuching)",
    "(GMT 8:00) China Standard Time (Asia/Macao)",
    "(GMT 8:00) Central Indonesia Time (Asia/Makassar)",
    "(GMT 8:00) Philippines Time (Asia/Manila)",
    "(GMT 8:00) China Standard Time (Asia/Shanghai)",
    "(GMT 8:00) Singapore Time (Asia/Singapore)",
    "(GMT 8:00) China Standard Time (Asia/Taipei)",
    "(GMT 8:00) Central Indonesia Time (Asia/Ujung_Pandang)",
    "(GMT 8:00) Ulaanbaatar Summer Time (Asia/Ulaanbaatar)",
    "(GMT 8:00) Ulaanbaatar Summer Time (Asia/Ulan_Bator)",
    "(GMT 8:00) China Standard Time (Asia/Urumqi)",
    "(GMT 8:00) Western Standard Time (Australia)(Australia/Perth)",
    "(GMT 8:00) Western Standard Time (Australia)(Australia/West)",
    "(GMT 8:00) China Standard Time (CTT)",
    "(GMT+08:00) GMT+08:00 (Etc/GMT-8)",
    "(GMT 8:00) China Standard Time (PRC)",
    "(GMT 8:00) Singapore Time (Singapore)",
    "(GMT 9:00) Choibalsan Summer Time (Asia/Choibalsan)",
    "(GMT 9:00) East Timor Time (Asia/Dili)",
    "(GMT 9:00) East Indonesia Time (Asia/Jayapura)",
    "(GMT 9:00) Korea Standard Time (Asia/Pyongyang)",
    "(GMT 9:00) Korea Standard Time (Asia/Seoul)",
    "(GMT 9:00) Japan Standard Time (Asia/Tokyo)",
    "(GMT 9:00) Yaktsk Summer Time (Asia/Yakutsk)",
    "(GMT+09:00) GMT+09:00 (Etc/GMT-9)",
    "(GMT 9:00) Japan Standard Time (JST)",
    "(GMT 9:00) Japan Standard Time (Japan)",
    "(GMT 9:00) Palau Time (Pacific/Palau)",
    "(GMT 9:00) Korea Standard Time (ROK)",
    "(GMT 9:30) Central Standard Time (Northern Territory)(ACT)",
    "(GMT 9:30) Central Standard Time (South Australia)(Australia/Adelaide)",
    "(GMT 9:30) Central Standard Time (South Australia/New South Wales)(Australia/Broken_Hill)",
    "(GMT 9:30) Central Standard Time (Northern Territory)(Australia/Darwin)",
    "(GMT 9:30) Central Standard Time (Northern Territory)(Australia/North)",
    "(GMT 9:30) Central Standard Time (South Australia)(Australia/South)",
    "(GMT 9:30) Central Standard Time (South Australia/New South Wales)(Australia/Yancowinna)",
    "(GMT 10:00) Eastern Standard Time (New South Wales)(AET)",
    "(GMT 10:00) Dumont-d Urville Time (Antarctica/DumontDUrville)",
    "(GMT 10:00) Sakhalin Summer Time (Asia/Sakhalin)",
    "(GMT 10:00) Vladivostok Summer Time (Asia/Vladivostok)",
    "(GMT 10:00) Eastern Standard Time (New South Wales)(Australia/ACT)",
    "(GMT 10:00) Eastern Standard Time (Queensland)(Australia/Brisbane)",
    "(GMT 10:00) Eastern Standard Time (New South Wales)(Australia/Canberra)",
    "(GMT 10:00) Eastern Standard Time (New South Wales)(Australia/Currie)",
    "(GMT 10:00) Eastern Standard Time (Tasmania)(Australia/Hobart)",
    "(GMT 10:00) Eastern Standard Time (Queensland)(Australia/Lindeman)",
    "(GMT 10:00) Eastern Standard Time (Victoria)(Australia/Melbourne)",
    "(GMT 10:00) Eastern Standard Time (New South Wales)(Australia/NSW)",
    "(GMT 10:00) Eastern Standard Time (Queensland)(Australia/Queensland)",
    "(GMT 10:00) Eastern Standard Time (New South Wales)(Australia/Sydney)",
    "(GMT 10:00) Eastern Standard Time (Tasmania)(Australia/Tasmania)",
    "(GMT 10:00) Eastern Standard Time (Victoria)(Australia/Victoria)",
    "(GMT+10:00) GMT+10:00 (Etc/GMT-10)(Etc/GMT-10)",
    "(GMT 10:00) Chamorro Standard Time (Pacific/Guam)",
    "(GMT 10:00) Papua New Guinea Time (Pacific/Port_Moresby)",
    "(GMT 10:00) Chamorro Standard Time (Pacific/Saipan)",
    "(GMT 10:00) Truk Time (Pacific/Truk)",
    "(GMT 10:00) Yap Time (Pacific/Yap)",
    "(GMT 10:30) Load Howe Standard Time (Australia/LHI)",
    "(GMT 10:30) Load Howe Standard Time (Australia/Lord_Howe)",
    "(GMT 11:00) Magadan Summer Time (Asia/Magadan)",
    "(GMT+11:00) GMT+11:00 (Etc/GMT-11)",
    "(GMT 11:00) Vanuatu Time (Pacific/Efate)",
    "(GMT 11:00) Solomon Is. Time (Pacific/Guadalcanal)",
    "(GMT 11:00) Kosrae Time (Pacific/Kosrae)",
    "(GMT 11:00) New Caledonia Time (Pacific/Noumea)",
    "(GMT 11:00) Ponape Time (Pacific/Ponape)",
    "(GMT 11:00) Solomon Is. Time (SST)",
    "(GMT 11:30) Norfolk Time (Pacific/Norfolk)",
    "(GMT 12:00) New Zealand Standard Time (Antarctica/McMurdo)",
    "(GMT 12:00) New Zealand Standard Time (Antarctica/South_Pole)",
    "(GMT 12:00) Anadyr Summer Time (Asia/Anadyr)",
    "(GMT 12:00) Petropavlovsk-Kamchatski Summer Time (Asia/Kamchatka)",
    "(GMT+12:00) GMT+12:00 (Etc/GMT-12)",
    "(GMT 12:00) Marshall Islands Time (Kwajalein)",
    "(GMT 12:00) New Zealand Standard Time (NST)",
    "(GMT 12:00) New Zealand Standard Time (NZ)",
    "(GMT 12:00) New Zealand Standard Time (Pacific/Auckland)",
    "(GMT 12:00) Fiji Time (Pacific/Fiji)",
    "(GMT 12:00) Tuvalu Time (Pacific/Funafuti)",
    "(GMT 12:00) Marshall Islands Time (Pacific/Kwajalein)",
    "(GMT 12:00) Marshall Islands Time (Pacific/Majuro)",
    "(GMT 12:00) Nauru Time (Pacific/Nauru)",
    "(GMT 12:00) Gilbert Is. Time (Pacific/Tarawa)",
    "(GMT 12:00) Wake Time (Pacific/Wake)",
    "(GMT 12:00) Wallis & Futuna Time (Pacific/Wallis)",
    "(GMT 12:45) Chatham Standard Time (NZ-CHAT)",
    "(GMT 12:45) Chatham Standard Time (Pacific/Chatham)",
    "(GMT+13:00) GMT+13:00 (Etc/GMT-13)",
    "(GMT 13:00) Phoenix Is. Time (Pacific/Enderbury)",
    "(GMT 13:00) Tonga Time (Pacific/Tongatapu)",
    "(GMT+14:00) GMT+14:00 (Etc/GMT-14)",
    "(GMT 14:00) Line Is. Time (Pacific/Kiritimati)",
    "(GMT -6:00) Central Standard Time (America/Resolute)",
    "(GMT -7:00) Mountain Standard Time (America/Creston)"
];
