/**
 * Reports Catalog
 * System report definitions used by Reports module.
 */

export type ReportType = "system" | "custom";

export interface ReportCategoryDefinition {
  key: string;
  name: string;
  description?: string;
}

export interface ReportDefinition {
  key: string;
  name: string;
  category: string;
  description?: string;
  reportType: ReportType;
  supportsChart?: boolean;
  supportsSchedule?: boolean;
  supportsShare?: boolean;
  supportsExport?: boolean;
  customizable?: boolean;
}

export const REPORT_CATEGORIES: ReportCategoryDefinition[] = [
  { key: "business_overview", name: "Business Overview" },
  { key: "sales", name: "Sales" },
  { key: "inventory", name: "Inventory" },
  { key: "receivables", name: "Receivables" },
  { key: "payments_received", name: "Payments Received" },
  { key: "payables", name: "Payables" },
  { key: "purchases_and_expenses", name: "Purchases and Expenses" },
  { key: "taxes", name: "Taxes" },
  { key: "projects_and_timesheet", name: "Projects and Timesheet" },
  { key: "accountant", name: "Accountant" },
  { key: "budgets", name: "Budgets" },
  { key: "currency", name: "Currency" },
  { key: "activity", name: "Activity" },
  { key: "automation", name: "Automation" },
  { key: "banking", name: "Banking" },
];

export const SYSTEM_REPORTS: ReportDefinition[] = [
  // Business Overview
  {
    key: "profit_and_loss",
    name: "Profit and Loss",
    category: "Business Overview",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
    customizable: true,
  },
  {
    key: "cash_flow_statement",
    name: "Cash Flow Statement",
    category: "Business Overview",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
    customizable: true,
  },
  {
    key: "balance_sheet",
    name: "Balance Sheet",
    category: "Business Overview",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
    customizable: true,
  },
  {
    key: "business_performance_ratio",
    name: "Business Performance Ratio",
    category: "Business Overview",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "cash_flow_forecasting",
    name: "Cash Flow Forecasting",
    category: "Business Overview",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "movement_of_equity",
    name: "Movement of Equity",
    category: "Business Overview",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },

  // Sales
  {
    key: "sales_by_customer",
    name: "Sales by Customer",
    category: "Sales",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "sales_by_item",
    name: "Sales by Item",
    category: "Sales",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "sales_by_sales_person",
    name: "Sales by Sales Person",
    category: "Sales",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "sales_summary",
    name: "Sales Summary",
    category: "Sales",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },

  // Inventory
  {
    key: "inventory_summary",
    name: "Inventory Summary",
    category: "Inventory",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "inventory_valuation_summary",
    name: "Inventory Valuation Summary",
    category: "Inventory",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "fifo_cost_lot_tracking",
    name: "FIFO Cost Lot Tracking",
    category: "Inventory",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: false,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "abc_classification",
    name: "ABC Classification",
    category: "Inventory",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "inventory_adjustment_summary",
    name: "Inventory Adjustment Summary",
    category: "Inventory",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "inventory_adjustment_details",
    name: "Inventory Adjustment Details",
    category: "Inventory",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },

  // Receivables
  {
    key: "customer_balance_summary",
    name: "Customer Balance Summary",
    category: "Receivables",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "aging_summary",
    name: "Aging Summary",
    category: "Receivables",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "aging_details",
    name: "Aging Details",
    category: "Receivables",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "invoice_details",
    name: "Invoice Details",
    category: "Receivables",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
    customizable: true,
  },
  {
    key: "retainer_invoice_details",
    name: "Retainer Invoice Details",
    category: "Receivables",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "sales_order_details",
    name: "Sales Order Details",
    category: "Receivables",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "quote_details",
    name: "Quote Details",
    category: "Receivables",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },

  // Payments Received
  {
    key: "payments_received",
    name: "Payments Received",
    category: "Payments Received",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "time_to_get_paid",
    name: "Time to Get Paid",
    category: "Payments Received",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "credit_note_details",
    name: "Credit Note Details",
    category: "Payments Received",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "refund_history",
    name: "Refund History",
    category: "Payments Received",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },

  // Payables
  {
    key: "vendor_balance_summary",
    name: "Vendor Balance Summary",
    category: "Payables",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "ap_aging_summary",
    name: "AP Aging Summary",
    category: "Payables",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "ap_aging_details",
    name: "AP Aging Details",
    category: "Payables",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "vendor_credit_details",
    name: "Vendor Credit Details",
    category: "Payables",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "payments_made",
    name: "Payments Made",
    category: "Payables",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "purchase_order_details",
    name: "Purchase Order Details",
    category: "Payables",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "purchase_orders_by_vendor",
    name: "Purchase Orders by Vendor",
    category: "Payables",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "payable_summary",
    name: "Payable Summary",
    category: "Payables",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "payable_details",
    name: "Payable Details",
    category: "Payables",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },

  // Purchases and Expenses
  {
    key: "purchases_by_vendor",
    name: "Purchases by Vendor",
    category: "Purchases and Expenses",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "purchases_by_item",
    name: "Purchases by Item",
    category: "Purchases and Expenses",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "expense_details",
    name: "Expense Details",
    category: "Purchases and Expenses",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "expenses_by_category",
    name: "Expenses by Category",
    category: "Purchases and Expenses",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "expenses_by_customer",
    name: "Expenses by Customer",
    category: "Purchases and Expenses",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "expenses_by_project",
    name: "Expenses by Project",
    category: "Purchases and Expenses",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "expenses_by_employee",
    name: "Expenses by Employee",
    category: "Purchases and Expenses",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "billable_expense_details",
    name: "Billable Expense Details",
    category: "Purchases and Expenses",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },

  // Projects and Timesheet
  {
    key: "timesheet_details",
    name: "Timesheet Details",
    category: "Projects and Timesheet",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "timesheet_profitability_summary",
    name: "Timesheet Profitability Summary",
    category: "Projects and Timesheet",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "project_summary",
    name: "Project Summary",
    category: "Projects and Timesheet",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "project_details",
    name: "Project Details",
    category: "Projects and Timesheet",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "projects_cost_summary",
    name: "Projects Cost Summary",
    category: "Projects and Timesheet",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "projects_revenue_summary",
    name: "Projects Revenue Summary",
    category: "Projects and Timesheet",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "projects_performance_summary",
    name: "Projects Performance Summary",
    category: "Projects and Timesheet",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },

  // Accountant
  {
    key: "account_transactions",
    name: "Account Transactions",
    category: "Accountant",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "account_type_summary",
    name: "Account Type Summary",
    category: "Accountant",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "general_ledger",
    name: "General Ledger",
    category: "Accountant",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "trial_balance",
    name: "Trial Balance",
    category: "Accountant",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },

  // Budgets
  {
    key: "budget_vs_actuals",
    name: "Budget Vs Actuals",
    category: "Budgets",
    reportType: "system",
    supportsChart: true,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },

  // Currency
  {
    key: "realized_gain_or_loss",
    name: "Realized Gain or Loss",
    category: "Currency",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "unrealized_gain_or_loss",
    name: "Unrealized Gain or Loss",
    category: "Currency",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },

  // Activity
  {
    key: "activity_logs",
    name: "Activity Logs",
    category: "Activity",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },

  // Taxes
  {
    key: "overseas_tax_summary",
    name: "Overseas Tax Summary Report",
    category: "Taxes",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "vat_moss_report",
    name: "VAT Moss Report",
    category: "Taxes",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "oss_ioss_scheme_report",
    name: "OSS/IOSS Scheme Report",
    category: "Taxes",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "reverse_charge_summary",
    name: "Reverse Charge Summary Report",
    category: "Taxes",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "sales_reverse_charge_summary",
    name: "Sales Reverse Charge Summary Report",
    category: "Taxes",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: true,
    supportsShare: true,
    supportsExport: true,
  },
  {
    key: "fec_report",
    name: "FEC Report",
    category: "Taxes",
    reportType: "system",
    supportsChart: false,
    supportsSchedule: false,
    supportsShare: true,
    supportsExport: true,
  },
];

export const SYSTEM_REPORT_MAP: Record<string, ReportDefinition> = SYSTEM_REPORTS.reduce(
  (acc, report) => {
    acc[report.key] = report;
    return acc;
  },
  {} as Record<string, ReportDefinition>
);

export const getSystemReportByKey = (key: string): ReportDefinition | undefined => {
  return SYSTEM_REPORT_MAP[key];
};

